<a href="https://colab.research.google.com/github/vishnujat5/AWS-ML-Python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/vishnujat5/AWS-ML-Python/refs/heads/main/file.csv"

df = pd.read_csv(url)
print(df)

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/vishnujat5/AWS-ML-Python/refs/heads/main/file.xlsx"

df = pd.read_excel(url)
print(df)

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/vishnujat5/AWS-ML-Python/refs/heads/main/data.json"

df = pd.read_json(url)
print(df)

       name  age
0    nikhil   10
1  devendra   20
2       raj   30
3     hello   40

In [2]:
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [3]:
df.head(3)

      name gender  physics  maths  english
0     arun   Male       88     87       78
1   rajesh   Male       96    100       95
2  moorthy   Male       89     90       70

In [4]:
df.tail(-3)

       name  gender  physics  maths  english
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [5]:
df.describe()

          physics       maths     english
count   14.000000   14.000000   14.000000
mean    65.857143   71.285714   69.857143
std     26.046872   24.237379   21.205432
min     12.000000   25.000000   23.000000
25%     56.000000   48.250000   67.000000
50%     69.000000   79.000000   74.000000
75%     85.500000   89.750000   78.000000
max    100.000000  100.000000  100.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     14 non-null     object
 1   gender   14 non-null     object
 2   physics  14 non-null     int64
 3   maths    14 non-null     int64
 4   english  14 non-null     int64
dtypes: int64(3), object(2)
memory usage: 692.0+ bytes

In [9]:
df.rename(columns={"name":"f_name"},inplace=True)

In [10]:
df

     f_name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [11]:
df.shape

(14, 5)

In [12]:
df['f_name']

0        arun
1      rajesh
2     moorthy
3        raja
4        usha
5       priya
6      Sundar
7     Kavitha
8      Dinesh
9        Hema
10      Gowri
11        Ram
12    Murugan
13    Jenifer
Name: f_name, dtype: object

In [13]:
type(df['english'])

pandas.core.series.Series

In [20]:
df['sum'] = df[['maths','physics','english']].sum(axis=1)

In [21]:
df

     f_name  gender  physics  maths  english       Mean  sum
0      arun    Male       88     87       78  71.285714  253
1    rajesh    Male       96    100       95  71.285714  291
2   moorthy    Male       89     90       70  71.285714  249
3      raja    Male       30     25       40  71.285714   95
4      usha  Female       67     45       78  71.285714  190
5     priya  Female       56     46       78  71.285714  180
6    Sundar    Male       12     67       67  71.285714  146
7   Kavitha  Female       78     71       67  71.285714  216
8    Dinesh    Male       56     45       67  71.285714  168
9      Hema  Female       71     90       23  71.285714  184
10    Gowri  Female      100    100      100  71.285714  300
11      Ram    Male       78     55       47  71.285714  180
12  Murugan    Male       34     89       78  71.285714  201
13  Jenifer  Female       67     88       90  71.285714  245

In [24]:
df.drop("Mean",axis=1,inplace=True)

In [25]:
df

     f_name  gender  physics  maths  english  sum
0      arun    Male       88     87       78  253
1    rajesh    Male       96    100       95  291
2   moorthy    Male       89     90       70  249
3      raja    Male       30     25       40   95
4      usha  Female       67     45       78  190
5     priya  Female       56     46       78  180
6    Sundar    Male       12     67       67  146
7   Kavitha  Female       78     71       67  216
8    Dinesh    Male       56     45       67  168
9      Hema  Female       71     90       23  184
10    Gowri  Female      100    100      100  300
11      Ram    Male       78     55       47  180
12  Murugan    Male       34     89       78  201
13  Jenifer  Female       67     88       90  245

In [26]:
df.loc[0:1,"f_name":"gender"]

   f_name gender
0    arun   Male
1  rajesh   Male

In [30]:
df.iloc[0:6,[0,5]]

    f_name  sum
0     arun  253
1   rajesh  291
2  moorthy  249
3     raja   95
4     usha  190
5    priya  180

In [32]:
df[df['sum']>150]

     f_name  gender  physics  maths  english  sum
0      arun    Male       88     87       78  253
1    rajesh    Male       96    100       95  291
2   moorthy    Male       89     90       70  249
4      usha  Female       67     45       78  190
5     priya  Female       56     46       78  180
7   Kavitha  Female       78     71       67  216
8    Dinesh    Male       56     45       67  168
9      Hema  Female       71     90       23  184
10    Gowri  Female      100    100      100  300
11      Ram    Male       78     55       47  180
12  Murugan    Male       34     89       78  201
13  Jenifer  Female       67     88       90  245

In [33]:
df.sort_values("sum",ascending=False)

     f_name  gender  physics  maths  english  sum
10    Gowri  Female      100    100      100  300
1    rajesh    Male       96    100       95  291
0      arun    Male       88     87       78  253
2   moorthy    Male       89     90       70  249
13  Jenifer  Female       67     88       90  245
7   Kavitha  Female       78     71       67  216
12  Murugan    Male       34     89       78  201
4      usha  Female       67     45       78  190
9      Hema  Female       71     90       23  184
5     priya  Female       56     46       78  180
11      Ram    Male       78     55       47  180
8    Dinesh    Male       56     45       67  168
6    Sundar    Male       12     67       67  146
3      raja    Male       30     25       40   95